function [pixelBox, pixelCenter] = HOGSpaceToPixelSpace(VOCopts, HOGCenter)
pixelCenter = (HOGCenter+1)* VOCopts.cellsize;
pixelBox = [pixelCenter(1) - (VOCopts.firstdim*VOCopts.cellsize)/2; ...
    pixelCenter(1) + (VOCopts.firstdim*VOCopts.cellsize)/2; ...
    pixelCenter(2) - (VOCopts.seconddim*VOCopts.cellsize)/2; ...
    pixelCenter(2) + (VOCopts.seconddim*VOCopts.cellsize)/2;];
end