function [pixelBox, pixelCenter] = HOGSpaceToPixelSpace(VOCopts, HOGCenter, pyramidIndex)
pixelCenter = (HOGCenter+1)* VOCopts.cellsize;
pixelBox = [pixelCenter(1) - ((1/VOCopts.pyramidscale)^(pyramidIndex-1)) * (VOCopts.firstdim*VOCopts.cellsize)/2; ...
    pixelCenter(1) + ((1/VOCopts.pyramidscale)^(pyramidIndex-1)) *(VOCopts.firstdim*VOCopts.cellsize)/2; ...
    pixelCenter(2) - ((1/VOCopts.pyramidscale)^(pyramidIndex-1)) *(VOCopts.seconddim*VOCopts.cellsize)/2; ...
    pixelCenter(2) + ((1/VOCopts.pyramidscale)^(pyramidIndex-1)) *(VOCopts.seconddim*VOCopts.cellsize)/2;];
end